"""local computer current_msi_version

Revision ID: 003dfc08b50c
Revises: dfa0100473b9
Create Date: 2023-03-22 16:17:37.711853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003dfc08b50c'
down_revision = 'dfa0100473b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('current_msi_version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'current_msi_version')
    # ### end Alembic commands ###
