"""pcc_access_tokens_model

Revision ID: 09795137a07c
Revises: 81c70d1cfb4b
Create Date: 2023-07-31 17:53:43.963698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09795137a07c'
down_revision = '81c70d1cfb4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcc_access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pcc_access_tokens')
    # ### end Alembic commands ###
