"""Add new fields to User

Revision ID: 0a2873537ed3
Revises: 0f35a16ff79a
Create Date: 2023-01-11 15:40:46.466356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2873537ed3'
down_revision = '0f35a16ff79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sftp_username', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('sftp_password', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('sftp_folder_path', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('client', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('folder_password', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('last_download_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_time_online', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_time_online')
    op.drop_column('users', 'last_download_time')
    op.drop_column('users', 'folder_password')
    op.drop_column('users', 'location')
    op.drop_column('users', 'client')
    op.drop_column('users', 'sftp_folder_path')
    op.drop_column('users', 'sftp_password')
    op.drop_column('users', 'sftp_username')
    # ### end Alembic commands ###
