"""pcc_2_legged_access_token

Revision ID: 0b5b3a31d139
Revises: 4d42a2fa54a1
Create Date: 2023-08-16 18:06:07.693045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0b5b3a31d139"
down_revision = "4d42a2fa54a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pcc_access_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_in", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.add_column(
        "companies", sa.Column("pcc_org_id", sa.String(length=128), nullable=True)
    )
    op.add_column("locations", sa.Column("pcc_fac_id", sa.Integer(), nullable=True))
    op.add_column(
        "locations",
        sa.Column(
            "use_pcc_backup",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "use_pcc_backup")
    op.drop_column("locations", "pcc_fac_id")
    op.drop_column("companies", "pcc_org_id")
    op.drop_table("pcc_access_tokens")
    # ### end Alembic commands ###
