"""edit computer nullable

Revision ID: 18ab006a00af
Revises: 7795f8209b66
Create Date: 2023-01-20 12:19:12.347548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ab006a00af'
down_revision = '7795f8209b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('computers', 'location_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('computers', 'identifier_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('computers', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('locations', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('computers', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('computers', 'identifier_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('computers', 'location_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
