"""fk_replace_company_name_on_id

Revision ID: 194cdc9cc3a3
Revises: 220cf3eb048a
Create Date: 2023-09-26 11:00:04.986623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "194cdc9cc3a3"
down_revision = "220cf3eb048a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("computers_company_name_fkey", "computers", type_="foreignkey")
    op.create_foreign_key(
        "fkey_computers_company_id",
        "computers",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("computers", "company_name")
    op.drop_constraint("locations_company_name_fkey", "locations", type_="foreignkey")
    op.create_foreign_key(
        "fkey_locations_company_id",
        "locations",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("locations", "company_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column("company_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("fkey_locations_company_id", "locations", type_="foreignkey")
    op.create_foreign_key(
        "locations_company_name_fkey",
        "locations",
        "companies",
        ["company_name"],
        ["name"],
        ondelete="CASCADE",
    )
    op.add_column(
        "computers",
        sa.Column("company_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("fkey_computers_company_id", "computers", type_="foreignkey")
    op.create_foreign_key(
        "computers_company_name_fkey",
        "computers",
        "companies",
        ["company_name"],
        ["name"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
