"""computer_soft_deletion

Revision ID: 19da2d49c75a
Revises: 2690033fd30e
Create Date: 2023-11-07 11:51:22.188222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19da2d49c75a"
down_revision = "2690033fd30e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "computers",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("computers", "is_deleted")
    # ### end Alembic commands ###
