"""Add download_status to User

Revision ID: 255015bb45d7
Revises: 6d4f2a034adc
Create Date: 2023-01-12 12:28:56.121124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255015bb45d7'
down_revision = '6d4f2a034adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('download_status', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'download_status')
    # ### end Alembic commands ###
