"""required_company_for_location

Revision ID: 2690033fd30e
Revises: 59b3deef2bc1
Create Date: 2023-11-06 14:55:26.009740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2690033fd30e"
down_revision = "59b3deef2bc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "locations", "company_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "locations", "company_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
