"""location_groups

Revision ID: 2897a3e5a4f1
Revises: 76ec624a6886
Create Date: 2023-10-06 10:50:44.258632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2897a3e5a4f1"
down_revision = "76ec624a6886"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "locations_to_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("location_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_group_id"],
            ["location_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("locations_to_groups")
    op.drop_table("location_groups")
    # ### end Alembic commands ###
