"""init

Revision ID: 2d3412c8c5a4
Revises: 
Create Date: 2023-01-25 18:17:22.423846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3412c8c5a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('manager_host', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('asociated_with', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'asociated_with')
    op.drop_column('computers', 'manager_host')
    # ### end Alembic commands ###
