"""fix field name

Revision ID: 300f7b595ca2
Revises: 84dbe7043bbf
Create Date: 2024-09-06 16:11:51.915981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300f7b595ca2'
down_revision = '84dbe7043bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('computers_max_count', sa.Integer(), server_default='1', nullable=False))
    op.drop_column('locations', 'computers__max_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('computers__max_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_column('locations', 'computers_max_count')
    # ### end Alembic commands ###
