"""notes

Revision ID: 356e5c8ad8e8
Revises: 9eafe86d0cf1
Create Date: 2024-04-08 12:15:29.356097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356e5c8ad8e8'
down_revision = '9eafe86d0cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'notes')
    # ### end Alembic commands ###
