"""user_required_company

Revision ID: 3ab2ceb40929
Revises: a230249243e2
Create Date: 2023-10-11 18:32:23.706330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ab2ceb40929"
down_revision = "a230249243e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "company_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "company_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
