"""alert controls

Revision ID: 3d353324b07e
Revises: 39f88ac5eede
Create Date: 2023-05-09 14:53:08.745075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d353324b07e'
down_revision = '39f88ac5eede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_controls', sa.Column('alert_interval', sa.String(length=64), nullable=False))
    op.add_column('alert_controls', sa.Column('key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_controls', 'key')
    op.drop_column('alert_controls', 'alert_interval')
    # ### end Alembic commands ###
