"""indentifier key for User

Revision ID: 40d0278a57fe
Revises: 0a2873537ed3
Create Date: 2023-01-11 18:02:22.016038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d0278a57fe'
down_revision = '0a2873537ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identifier_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'identifier_key')
    # ### end Alembic commands ###
