"""location default_sftp_path

Revision ID: 427d7850814b
Revises: a44ebb1d49cc
Create Date: 2023-04-28 13:08:59.313744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427d7850814b'
down_revision = 'a44ebb1d49cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('default_sftp_path', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'default_sftp_path')
    # ### end Alembic commands ###
