"""pcc_vs_manual_companies

Revision ID: 461a992b352b
Revises: dd1be74b7454
Create Date: 2023-09-11 17:00:43.019961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "461a992b352b"
down_revision = "dd1be74b7454"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "created_from_pcc",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "locations",
        sa.Column(
            "created_from_pcc",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "created_from_pcc")
    op.drop_column("companies", "created_from_pcc")
    # ### end Alembic commands ###
