"""system_logs_required_fields

Revision ID: 4d42a2fa54a1
Revises: 5167278c8852
Create Date: 2023-08-11 12:36:16.084352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d42a2fa54a1'
down_revision = '5167278c8852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('system_logs', 'object_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('system_logs', 'object_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('system_logs', 'object_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_logs', 'object_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('system_logs', 'object_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('system_logs', 'object_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('system_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
