"""system_logs

Revision ID: 5167278c8852
Revises: a6a760e24123
Create Date: 2023-08-10 17:15:33.392777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "5167278c8852"
down_revision = "a6a760e24123"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "log_type",
            sa.Enum(
                "USER_CREATED",
                "USER_UPDATED",
                "USER_DELETED",
                "COMPUTER_CREATED",
                "COMPUTER_UPDATED",
                "COMPUTER_DELETED",
                "COMPANY_CREATED",
                "COMPANY_UPDATED",
                "COMPANY_DELETED",
                "LOCATION_CREATED",
                "LOCATION_UPDATED",
                "LOCATION_DELETED",
                "ALERT_CREATED",
                "ALERT_UPDATED",
                "ALERT_DELETED",
                name="systemlogtype",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("object_id", sa.Integer(), nullable=True),
        sa.Column("object_name", sa.String(length=128), nullable=True),
        sa.Column("object_url", sa.String(length=256), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_logs")

    system_log_type = postgresql.ENUM(
        "USER_CREATED",
        "USER_UPDATED",
        "USER_DELETED",
        "COMPUTER_CREATED",
        "COMPUTER_UPDATED",
        "COMPUTER_DELETED",
        "COMPANY_CREATED",
        "COMPANY_UPDATED",
        "COMPANY_DELETED",
        "LOCATION_CREATED",
        "LOCATION_UPDATED",
        "LOCATION_DELETED",
        "ALERT_CREATED",
        "ALERT_UPDATED",
        "ALERT_DELETED",
        name="systemlogtype",
    )
    system_log_type.drop(op.get_bind())
    # ### end Alembic commands ###
