"""total computer count for company and location

Revision ID: 540d214a8e3c
Revises: 5be54e513eaf
Create Date: 2023-02-28 17:00:52.399565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540d214a8e3c'
down_revision = '5be54e513eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('locations_per_company', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('computers_per_location', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'computers_per_location')
    op.drop_column('companies', 'locations_per_company')
    # ### end Alembic commands ###
