"""monitor_api_calls_and_alerts

Revision ID: 59b3deef2bc1
Revises: 8beda48038ff
Create Date: 2023-11-01 11:45:58.216298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "59b3deef2bc1"
down_revision = "8beda48038ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column(
            "alert_type",
            sa.Enum("PRIMARY_COMPUTER_DOWN", "CRITICAL_ALERT", name="alerteventtype"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "download_backup_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("computer_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["computer_id"], ["computers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("download_backup_calls")
    op.drop_table("alert_events")

    alert_event_type = postgresql.ENUM(
        "PRIMARY_COMPUTER_DOWN",
        "CRITICAL_ALERT",
        name="alerteventtype",
    )
    alert_event_type.drop(op.get_bind())
    # ### end Alembic commands ###
