"""count_api_calls_and_alerts

Revision ID: 60f6228d16db
Revises: 8beda48038ff
Create Date: 2023-10-30 17:25:15.877185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60f6228d16db"
down_revision = "8beda48038ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "last_billing_report",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "computers",
        sa.Column("pcc_api_calls", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "locations",
        sa.Column("critical_alerts", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "critical_alerts")
    op.drop_column("computers", "pcc_api_calls")
    op.drop_column("companies", "last_billing_report")
    # ### end Alembic commands ###
