"""init

Revision ID: 632045337307
Revises: 
Create Date: 2023-01-26 15:49:27.090587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632045337307'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('asociated_with', sa.String(length=128), nullable=True),
    sa.Column('last_time_online', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_name'], ['companies.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('computers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computer_name', sa.String(length=64), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('alert_status', sa.String(length=128), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sftp_host', sa.String(length=128), nullable=True),
    sa.Column('sftp_username', sa.String(length=64), nullable=True),
    sa.Column('sftp_password', sa.String(length=128), nullable=True),
    sa.Column('sftp_folder_path', sa.String(length=256), nullable=True),
    sa.Column('folder_password', sa.String(length=128), nullable=True),
    sa.Column('download_status', sa.String(length=64), nullable=True),
    sa.Column('last_download_time', sa.DateTime(), nullable=True),
    sa.Column('last_time_online', sa.DateTime(), nullable=True),
    sa.Column('identifier_key', sa.String(length=128), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('manager_host', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_name'], ['companies.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_name'], ['locations.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('computer_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computers')
    op.drop_table('locations')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
