"""fk_replace_location_name_on_id

Revision ID: 683ba442f443
Revises: c35ffa12d355
Create Date: 2023-09-25 15:00:54.489235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "683ba442f443"
down_revision = "c35ffa12d355"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("computers_location_name_fkey", "computers", type_="foreignkey")
    op.create_foreign_key(
        "computers_location_id_fkey",
        "computers",
        "locations",
        ["location_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("computers", "location_name")
    op.drop_constraint("locations_name_key", "locations", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("locations_name_key", "locations", ["name"])
    op.add_column(
        "computers",
        sa.Column("location_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("computers_location_id_fkey", "computers", type_="foreignkey")
    op.create_foreign_key(
        "computers_location_name_fkey",
        "computers",
        "locations",
        ["location_name"],
        ["name"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
