"""Add sftp_host to User

Revision ID: 6d4f2a034adc
Revises: 40d0278a57fe
Create Date: 2023-01-12 10:56:48.617711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4f2a034adc'
down_revision = '40d0278a57fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sftp_host', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sftp_host')
    # ### end Alembic commands ###
