"""fk_replace_flag_name_on_id

Revision ID: 6e7842b97fdb
Revises: 614e71ec07ce
Create Date: 2023-09-26 15:46:29.614179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e7842b97fdb"
down_revision = "614e71ec07ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "desktop_clients_flag_name_fkey", "desktop_clients", type_="foreignkey"
    )
    op.create_foreign_key(
        "fkey_desktop_clients_flag_id",
        "desktop_clients",
        "client_versions",
        ["flag_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("desktop_clients", "flag_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "desktop_clients",
        sa.Column("flag_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "fkey_desktop_clients_flag_id", "desktop_clients", type_="foreignkey"
    )
    op.create_foreign_key(
        "desktop_clients_flag_name_fkey",
        "desktop_clients",
        "client_versions",
        ["flag_name"],
        ["name"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
