"""soft_delete_companies

Revision ID: 709b7988d26c
Revises: ef2fdb822c51
Create Date: 2023-11-09 16:22:31.999597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "709b7988d26c"
down_revision = "ef2fdb822c51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.add_column("companies", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.drop_constraint("fkey_computers_company_id", "computers", type_="foreignkey")
    op.create_foreign_key(
        "fkey_computers_company_id", "computers", "companies", ["company_id"], ["id"]
    )
    op.drop_constraint("fkey_locations_company_id", "locations", type_="foreignkey")
    op.create_foreign_key(
        "fkey_locations_company_id", "locations", "companies", ["company_id"], ["id"]
    )
    op.drop_constraint(
        "fk_company_id_companies", "pcc_creation_reports", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_company_id_companies",
        "pcc_creation_reports",
        "companies",
        ["company_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_company_id_companies", "pcc_creation_reports", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_company_id_companies",
        "pcc_creation_reports",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("fkey_locations_company_id", "locations", type_="foreignkey")
    op.create_foreign_key(
        "fkey_locations_company_id",
        "locations",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fkey_computers_company_id", "computers", type_="foreignkey")
    op.create_foreign_key(
        "fkey_computers_company_id",
        "computers",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("companies", "deleted_at")
    op.drop_column("companies", "is_deleted")
    # ### end Alembic commands ###
