"""users alerts relationship

Revision ID: 756f49922fa9
Revises: 003dfc08b50c
Create Date: 2023-04-04 15:42:30.381155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756f49922fa9'
down_revision = '003dfc08b50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_alerts',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('alerts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alerts_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    op.create_unique_constraint(None, 'alerts', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='unique')
    op.drop_table('users_alerts')
    # ### end Alembic commands ###
