"""pcc_daily_requests

Revision ID: 76ec624a6886
Revises: f680e9979d73
Create Date: 2023-09-29 09:21:09.963783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76ec624a6886"
down_revision = "f680e9979d73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pcc_daily_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("requests_count", sa.Integer(), nullable=False),
        sa.Column("reset_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reset_time"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pcc_daily_requests")
    # ### end Alembic commands ###
