"""company_trial

Revision ID: 7bfb34e5195e
Revises: 709b7988d26c
Create Date: 2023-11-13 11:12:57.996622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfb34e5195e'
down_revision = '709b7988d26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_trial', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_trial')
    # ### end Alembic commands ###
