"""comp_logs_enabled_disabled

Revision ID: 7e6d90fed930
Revises: 4d42a2fa54a1
Create Date: 2023-08-21 15:55:45.535893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6d90fed930'
down_revision = '4d42a2fa54a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('last_time_logs_enabled', sa.DateTime(), nullable=True))
    op.add_column('computers', sa.Column('last_time_logs_disabled', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'last_time_logs_disabled')
    op.drop_column('computers', 'last_time_logs_enabled')
    # ### end Alembic commands ###
