"""computer ip

Revision ID: 81c70d1cfb4b
Revises: 3d353324b07e
Create Date: 2023-05-10 12:36:44.569020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c70d1cfb4b'
down_revision = '3d353324b07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('computer_ip', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'computer_ip')
    # ### end Alembic commands ###
