"""computers_max_count

Revision ID: 84dbe7043bbf
Revises: 225016f12bd4
Create Date: 2024-09-06 09:32:08.857297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84dbe7043bbf'
down_revision = '225016f12bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('computers__max_count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'computers__max_count')
    # ### end Alembic commands ###
