"""addirional_locations

Revision ID: 850558a69770
Revises: bac71dc4f32f
Create Date: 2024-04-02 12:13:19.150392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850558a69770'
down_revision = 'bac71dc4f32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computer_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('additional_locations')
    # ### end Alembic commands ###
