"""remove_alerts

Revision ID: 8beda48038ff
Revises: ef5d6c1cc368
Create Date: 2023-10-25 19:51:36.947762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8beda48038ff"
down_revision = "ef5d6c1cc368"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_alerts")
    op.drop_table("alert_controls")
    op.drop_table("alerts")
    op.drop_column("computers", "alert_status")
    op.drop_column("users", "asociated_with")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "asociated_with", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "computers",
        sa.Column(
            "alert_status", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "from_email", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column(
            "to_addresses", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column(
            "subject", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column("body", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column(
            "html_body", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
        sa.Column(
            "alert_status", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="alerts_pkey"),
        sa.UniqueConstraint("name", name="alerts_name_key"),
    )
    op.create_table(
        "alert_controls",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("alert_period", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("alert_associated", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "alert_interval", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column("key", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["alert_associated"],
            ["alerts.id"],
            name="alert_controls_alert_associated_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="alert_controls_pkey"),
        sa.UniqueConstraint("name", name="alert_controls_name_key"),
    )
    op.create_table(
        "users_alerts",
        sa.Column("users_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("alerts_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["alerts_id"], ["alerts.id"], name="users_alerts_alerts_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["users_id"], ["users.id"], name="users_alerts_users_id_fkey"
        ),
    )
    # ### end Alembic commands ###
