"""alert model

Revision ID: 8de64c2e7f6f
Revises: 9f3ee4b9f652
Create Date: 2023-02-15 15:09:56.829361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de64c2e7f6f'
down_revision = '9f3ee4b9f652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('from_email', sa.String(length=128), nullable=True),
    sa.Column('to_addresses', sa.String(length=128), nullable=True),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('body', sa.String(length=512), nullable=True),
    sa.Column('html_body', sa.String(length=512), nullable=True),
    sa.Column('alert_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###
