"""pcc_scans_and_creation_report

Revision ID: 98ae0eab3662
Revises: 780ce524d37c
Create Date: 2023-08-30 14:50:39.395128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "98ae0eab3662"
down_revision = "780ce524d37c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pcc_activations_scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "SUCCEED", "FAILED", name="scanstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pcc_creation_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pcc_creation_reports")
    op.drop_table("pcc_activations_scans")

    scan_status = postgresql.ENUM("IN_PROGRESS", "SUCCEED", "FAILED", name="scanstatus")
    scan_status.drop(op.get_bind())
    # ### end Alembic commands ###
