"""add sftp_folders_paths

Revision ID: 9eafe86d0cf1
Revises: 850558a69770
Create Date: 2024-04-02 15:47:55.325360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eafe86d0cf1'
down_revision = '850558a69770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('additional_sftp_folder_paths', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'additional_sftp_folder_paths')
    # ### end Alembic commands ###
