"""computer files_checksum JSON

Revision ID: 9f3ee4b9f652
Revises: fd03461f5c2e
Create Date: 2023-01-30 16:13:16.343646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3ee4b9f652'
down_revision = 'fd03461f5c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('files_checksum', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'files_checksum')
    # ### end Alembic commands ###
