"""activate_company_location

Revision ID: 9f7003fad01d
Revises: 7bfb34e5195e
Create Date: 2023-11-21 16:06:41.243386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f7003fad01d"
down_revision = "7bfb34e5195e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "activated", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.add_column(
        "companies", sa.Column("deactivated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "computers", sa.Column("deactivated_at", sa.DateTime(), nullable=True)
    )
    op.alter_column(
        "computers", "activated", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.add_column(
        "locations",
        sa.Column(
            "activated", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.add_column(
        "locations", sa.Column("deactivated_at", sa.DateTime(), nullable=True)
    )
    op.add_column("users", sa.Column("deactivated_at", sa.DateTime(), nullable=True))
    op.alter_column("users", "activated", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "activated", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("users", "deactivated_at")
    op.drop_column("locations", "deactivated_at")
    op.drop_column("locations", "activated")
    op.alter_column("computers", "activated", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("computers", "deactivated_at")
    op.drop_column("companies", "deactivated_at")
    op.drop_column("companies", "activated")
    # ### end Alembic commands ###
