"""company sftp username password

Revision ID: a44ebb1d49cc
Revises: 756f49922fa9
Create Date: 2023-04-04 16:22:12.682398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44ebb1d49cc'
down_revision = '756f49922fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('default_sftp_username', sa.String(length=128), nullable=True))
    op.add_column('companies', sa.Column('default_sftp_password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'default_sftp_password')
    op.drop_column('companies', 'default_sftp_username')
    # ### end Alembic commands ###
