"""remove_backup_calls_cascade_deleting

Revision ID: ae7edd05bb65
Revises: 19da2d49c75a
Create Date: 2023-11-07 18:44:19.681692

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "ae7edd05bb65"
down_revision = "19da2d49c75a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "download_backup_calls_computer_id_fkey",
        "download_backup_calls",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "download_backup_calls_computer_id_fkey",
        "download_backup_calls",
        "computers",
        ["computer_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "download_backup_calls_computer_id_fkey",
        "download_backup_calls",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "download_backup_calls_computer_id_fkey",
        "download_backup_calls",
        "computers",
        ["computer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
