"""computers_max_count_in_company

Revision ID: bed7e3d9a708
Revises: 225016f12bd4
Create Date: 2024-09-09 09:27:43.428048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed7e3d9a708'
down_revision = '225016f12bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('computers_max_count', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'computers_max_count')
    # ### end Alembic commands ###
