"""add_location_id_computer

Revision ID: c35ffa12d355
Revises: 461a992b352b
Create Date: 2023-09-22 16:50:42.249865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35ffa12d355'
down_revision = '461a992b352b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('location_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'location_id')
    # ### end Alembic commands ###
