"""printer_fields_to_computer

Revision ID: cd5377f00639
Revises: fdfede9322e9
Create Date: 2023-12-08 14:20:48.300096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5377f00639'
down_revision = 'fdfede9322e9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE TYPE printerstatus AS ENUM ('NORMAL', 'OFFLINE', 'UNKNOWN')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('printer_name', sa.String(length=128), nullable=True))
    op.add_column('computers', sa.Column('printer_status', sa.Enum('NORMAL', 'OFFLINE', 'UNKNOWN', name='printerstatus'), server_default=sa.text("'UNKNOWN'"), nullable=True))
    op.add_column('computers', sa.Column('printer_status_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'printer_status_timestamp')
    op.drop_column('computers', 'printer_status')
    op.drop_column('computers', 'printer_name')
    # ### end Alembic commands ###
    op.execute("DROP TYPE printerstatus")
