"""online and offline computers

Revision ID: dfa0100473b9
Revises: 540d214a8e3c
Create Date: 2023-02-28 17:24:19.053745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa0100473b9'
down_revision = '540d214a8e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('total_computers', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('computers_offline', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('computers_online', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('computers_offline', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('computers_online', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'computers_online')
    op.drop_column('locations', 'computers_offline')
    op.drop_column('companies', 'computers_online')
    op.drop_column('companies', 'computers_offline')
    op.drop_column('companies', 'total_computers')
    # ### end Alembic commands ###
