"""global_company

Revision ID: e3095a0b717e
Revises: 2897a3e5a4f1
Create Date: 2023-10-06 12:54:51.783243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.ext.automap import automap_base


# revision identifiers, used by Alembic.
revision = "e3095a0b717e"
down_revision = "2897a3e5a4f1"
branch_labels = None
depends_on = None


Base = automap_base()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "is_global", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###

    # Create Global Company
    bind = op.get_bind()
    Base.prepare(autoload_with=bind)
    Company = Base.classes.companies

    session = Session(bind=bind)
    new_company = Company(name="Global", is_global=True)
    session.add(new_company)
    session.commit()


def downgrade():
    # Delete Global Company while migration
    bind = op.get_bind()
    Base.prepare(autoload_with=bind)
    Company = Base.classes.companies

    session = Session(bind=bind)
    global_company = session.query(Company).filter_by(is_global=True).first()
    session.delete(global_company)
    session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "is_global")
    # ### end Alembic commands ###
