"""creation_reports_status

Revision ID: e7b58bd0e419
Revises: 1fae53c0e8ed
Create Date: 2023-09-04 15:11:10.766909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "e7b58bd0e419"
down_revision = "1fae53c0e8ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    creation_report_status = postgresql.ENUM(
        "WAITING",
        "APPROVED",
        "REJECTED",
        name="creationreportstatus",
    )
    creation_report_status.create(op.get_bind())

    op.add_column(
        "pcc_creation_reports",
        sa.Column(
            "status",
            sa.Enum("WAITING", "APPROVED", "REJECTED", name="creationreportstatus"),
            nullable=False,
        ),
    )
    op.add_column(
        "pcc_creation_reports",
        sa.Column("status_changed_by", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "pcc_creation_reports",
        sa.Column("status_changed_at", sa.DateTime(), nullable=True),
    )
    op.alter_column(
        "pcc_creation_reports", "company_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pcc_creation_reports", "company_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("pcc_creation_reports", "status_changed_at")
    op.drop_column("pcc_creation_reports", "status_changed_by")
    op.drop_column("pcc_creation_reports", "status")

    creation_report_status = postgresql.ENUM(
        "WAITING",
        "APPROVED",
        "REJECTED",
        name="creationreportstatus",
    )
    creation_report_status.drop(op.get_bind())
    # ### end Alembic commands ###
