"""deleted_at_field

Revision ID: eed5157011f7
Revises: ae7edd05bb65
Create Date: 2023-11-08 09:48:35.256653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eed5157011f7"
down_revision = "ae7edd05bb65"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("computers", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("computers", "deleted_at")
    # ### end Alembic commands ###
