"""soft_delete_users

Revision ID: ef2fdb822c51
Revises: f5fb40f5eaba
Create Date: 2023-11-09 12:47:10.698970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef2fdb822c51"
down_revision = "f5fb40f5eaba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_status_changed_by_id_users", "pcc_creation_reports", type_="foreignkey"
    )
    op.drop_column("pcc_creation_reports", "status_changed_by_id")
    op.add_column(
        "users",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
    )
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "is_deleted")
    op.add_column(
        "pcc_creation_reports",
        sa.Column(
            "status_changed_by_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "fk_status_changed_by_id_users",
        "pcc_creation_reports",
        "users",
        ["status_changed_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
