"""backup_logs

Revision ID: f646e7bf3921
Revises: 3dd242d5c889
Create Date: 2023-08-04 10:07:06.794594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "f646e7bf3921"
down_revision = "3dd242d5c889"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backup_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "backup_log_type",
            sa.Enum(
                "WITH_DOWNLOADS_PERIOD", "NO_DOWNLOADS_PERIOD", name="backuplogtype"
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("error", sa.String(length=128), server_default="", nullable=True),
        sa.Column("notes", sa.String(length=128), server_default="", nullable=True),
        sa.Column("computer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["computer_id"],
            ["computers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backup_logs")

    backup_log_type = postgresql.ENUM(
        "WITH_DOWNLOADS_PERIOD",
        "NO_DOWNLOADS_PERIOD",
        name="backuplogtype",
    )
    backup_log_type.drop(op.get_bind())
    # ### end Alembic commands ###
