"""device_location

Revision ID: fa64ea171be2
Revises: bed7e3d9a708
Create Date: 2024-09-10 11:53:32.618661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa64ea171be2'
down_revision = 'bed7e3d9a708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('computers', sa.Column('device_location', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('computers', 'device_location')
    # ### end Alembic commands ###
